<?php

include '00.php';
include 'total.php';

$qty = $_SESSION['credits'];

if(isset($_SESSION['hk_email'])){

$email = $_SESSION['hk_email'];

}else{
header("Location: https://texttoimagepro.com/?page_id=34");
}

?>

<!DOCTYPE html> 
<html lang="en-US">
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
Pay Now
</title>


    <link rel='stylesheet' href='css/woocommerce-layout.css' type='text/css' media='all' />
    <link rel='stylesheet' href='css/woocommerce-smallscreen.css' type='text/css' media='only screen and (max-width: 768px)' />
    <link rel='stylesheet' href='css/woocommerce.css' type='text/css' media='all' />
    <link rel='stylesheet' href='css/font-awesome.min.css' type='text/css' media='all' />
    <link rel='stylesheet' href='style.css' type='text/css' media='all' />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Oswald:400,500,700%7CRoboto:400,500,700%7CHerr+Von+Muellerhoff:400,500,700%7CQuattrocento+Sans:400,500,700' type='text/css' media='all' />
    <link rel='stylesheet' href='css/easy-responsive-shortcodes.css' type='text/css' media='all' />

  </head>
  <body class="home page page-template page-template-template-portfolio page-template-template-portfolio-php">

<div id='profile'></div>

<div id='start'>
<input type='text' id='amt' style='display:none;' value='<?php echo $_SESSION['amount']; ?>'>
<input type='text' id='username' style='display:none;' value='<?php echo $_SESSION['hk_email']; ?>'>

<?php

$total_buy2 = $total_buy1 + $qty;

if($total_credits >= $total_buy2){ 

?>

<h2>Press Here </h2>
<button id="rzp-button1">Pay</button>

<?php 
}else{ 

?>

<h1> due to some maintenance we can not sale credits right now...</h1>
<h2>please visit after some time.... or try with less credits value</h2>
<a href="https://texttoimagepro.com/?page_id=34"> click here to go to dashboard </a>
<p>sorry for inconviniance </p>

<?php } ?>
</div>

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>

var options = {
    "key": "<?php echo $_SESSION['api_key']; ?>",  // Enter the Key ID generated from the Dashboard
    "amount": "<?php echo $_SESSION['amount']; ?>", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "<?php echo $_SESSION['cur']; ?>",
    "name": "TextToImagePro",
    "description": "iQtesst Pro(file)",
    "image": "",
     "order_id": "<?php echo $_SESSION['order_id']; ?>", // Replace with the order_id generated by you in the backend.

    "handler": function (response){

  var xhttp = new XMLHttpRequest();

  xhttp.onreadystatechange = function() {

    if (this.readyState == 4 && this.status == 200) {



    }
  };

  xhttp.open("GET", "payment1.php?payment_id="+ response.razorpay_payment_id, true);

  xhttp.send();

document.getElementById('profile').innerHTML = '<a href="https://texttoimagepro.com/?page_id=34"><h1>click to Go to Dashboard</h1></a>';


    },
    "prefill": {
        "name": "",

        "email": "<?php $_SESSION['hk_email']; ?>",
        "contact": ""
    },
    "notes": {
        "address": ""
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){

});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();


document.getElementById('start').style.display = 'none';
document.getElementById('profile').innerHTML = '<h1>Please, give attention here. Do not press BACK. . .</h1>';

var amt = document.getElementById('amt').value;
var username = document.getElementById('username').value;


  var xhttp = new XMLHttpRequest();

  xhttp.onreadystatechange = function() {

    if (this.readyState == 4 && this.status == 200) {



    }
  };

  xhttp.open("GET", "payment1.php?amt="+ amt +"&email="+ username, true);

  xhttp.send();

}


</script>

    <script src='js/jquery.js'></script>
    <script src='js/plugins.js'></script>
    <script src='js/scripts.js'></script>
    <script src='js/masonry.pkgd.min.js'></script>
  </body>
</html>
