
<h5><a onclick="logout()">LogOut</a></h5><br><br>

<?php
include '00.php';
include 'remaining_credits.php';

if(isset($_SESSION['hk_email'])){
if($remaining_credits > 0){

echo '<h3 style="background-color: yellow; padding: 10px; text-align: center;"> You have '.$remaining_credits .' Credits Remain to Use. </h3>';
?>

<div style="font-family: Arial, sans-serif; text-align: center;">
    <div style="background-color: #f0f0f0; padding: 20px;">
        <h1 style="color: #333;">Text-to-Image Generation Steps</h1>

        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">1. Input your text prompt</div>
        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">2. Click the "Generate" button</div>
        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">3. Wait while your image is being generated</div>
        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">4. See your generated image</div>
        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">5. Download your image</div>
        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">6. Note that we do not save your image</div>
        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">7. Each generated image will cost 1 credit</div>
        <div class="step" style="margin: 20px; font-size: 18px; color: #666;">8. These images are generated by AI</div>

        <button class="button" style="background-color: #007BFF; color: #fff; border: none; padding: 10px 20px; font-size: 16px; cursor: pointer; transition: background-color 0.3s;" onclick="generateImageFront()">Go to Image Generation</button>
    </div>
</div>

<?php
} //if number 2 , which is about remaining credits  is end here
else{
echo '<h3 style="background-color: orange; padding: 10px; text-align: center;"> You have '.$remaining_credits .' Credits Remain to Use. </h3>';
?>


<?php
if(isset($_SESSION['free_credit'])){
    ?>
    <br><a href='https://texttoimagepro.com/?p=82'>
“Claim Your Free Credits – Up to 10 Credits.”
</a>
<?php } ?>


    <div style="max-width: 400px; margin: 0 auto; padding: 20px; border: 1px solid #ccc; border-radius: 10px; background-color: #f9f9f9; font-family: Arial, sans-serif;">
        <h3 style="text-align: center;">You need to buy credits</h3><br>
        <form>
            <label style="display: block; margin-top: 10px;">
                <input disabled type="radio" name="creditAmount" value="1" style="margin-right: 5px;"> <span style="font-weight: bold;">1 Credit in </span>($0.17 )
            </label>
            <label style="display: block; margin-top: 10px;">
                <input type="radio" name="creditAmount" value="10" style="margin-right: 5px;"> <span style="font-weight: bold;">10 Credits </span>($1.7 )
            </label>
            <label style="display: block; margin-top: 10px;">
                <input type="radio" name="creditAmount" value="50" style="margin-right: 5px;"> <span style="font-weight: bold;">50 Credits </span>($8.5 )
            </label>
            <label style="display: block; margin-top: 10px;">
                <input type="radio" name="creditAmount" value="100" style="margin-right: 5px;"> <span style="font-weight: bold;">100 Credits </span>($17.00 ) 
            </label><br>
            <button onclick="buy1()" type="button" style="display: block; margin: 20px auto; background-color: #007BFF; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;"> Next>> </button><br>
        </form>
    </div>

<?php
} //else of if number 2
} // if number 1 , which check session is end here

?>

<hr>
<br><h5><a onclick="profile2()">your Images History</a></h5><br>
<br><h5><a onclick="profile3()">your Payments History</a></h5>
<br><hr>
